name: Nicholas Stephan
favicon: null
layout_spectrum: 0.52126
typography_spectrum: 0.1784
title: Nicholas Stephan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcdbe0'
    - '#758278'
    - '#85a49f'
    - '#93b3b2'
    - '#647167'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
